#!/bin/bash

OPENSSL_SOURCE="Source/openssl-1.0.2s"
HOST_PLATFORM="linux-x86_64"
OPT_OPENSSL_SHARED=(1)
ANDROID_NDK_ROOT="/root/NDK/android-ndk-r18b"
OPT_TYPE=(armv7 arm64 x86 x86_64)
ANDROID_NDK_TOOLCHAIN_VER="4.9"
ANDROID_NDK_PLATFORM="android-21"